apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rdkafka-avro
  title: rdkafka-avro
  description: Missing description in repo
  links:
    - url: https://eurostar.slack.com/archives/C910RBMED
      icon: slack
      type: slack
      title: "#team-developers"
  annotations:
    github.com/project-slug: EurostarDigital/rdkafka-avro
    grafana/tag-selector: rdkafka-avro
    circleci.com/project-slug: github/EurostarDigital/rdkafka-avro

spec:
  type: service
  lifecycle: production
  owner: group:eurostardigital/developers
